/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Return all events sorted by document.published_at descending.
         */
        get: operations["list_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Return full EventDetail for a single event; 404 if not found.
         */
        get: operations["get_event_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument Timeline
         * @description Return instrument + events where primary_instrument_id matches; 404 if missing.
         */
        get: operations["get_instrument_timeline_instruments__instrument_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DocumentOut */
        DocumentOut: {
            /** Url */
            url: string;
            /** Source */
            source: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Title */
            title: string | null;
        };
        /** EventDetail */
        EventDetail: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /** Entities */
            entities: string[];
            /** Industries */
            industries: string[];
            /** Channels */
            channels: string[];
            /** Direction */
            direction: string;
            /** Horizon Days */
            horizon_days: number;
            /** Confidence */
            confidence: number;
            /** Surprise Score */
            surprise_score: number | null;
            /** Novelty Score */
            novelty_score: number | null;
            /** Source Reliability */
            source_reliability: number | null;
            /** Evidence */
            evidence: string[];
            /** Model */
            model: string;
            /** Model Version */
            model_version: string;
            document: components["schemas"]["DocumentOut"];
            /** Outcomes */
            outcomes: components["schemas"]["OutcomeOut"][];
        };
        /** EventSummary */
        EventSummary: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /** Direction */
            direction: string;
            /** Confidence */
            confidence: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Primary Ticker */
            primary_ticker: string | null;
            /** Instrument Name */
            instrument_name: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
        };
        /** InstrumentTimeline */
        InstrumentTimeline: {
            instrument: components["schemas"]["InstrumentOut"];
            /** Events */
            events: components["schemas"]["EventSummary"][];
        };
        /** OutcomeOut */
        OutcomeOut: {
            /** Horizon Days */
            horizon_days: number;
            /** Raw Return */
            raw_return: number | null;
            /** Market Return */
            market_return: number | null;
            /** Abnormal Return */
            abnormal_return: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
        };
    };
    get_event_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_timeline_instruments__instrument_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
